# DO NOT EDIT! This file was generated by jschema_to_python version 0.0.1.dev29,
# with extension for dataclasses and type annotation.

from onnxscript.diagnostics.infra.sarif._address import Address
from onnxscript.diagnostics.infra.sarif._artifact import Artifact
from onnxscript.diagnostics.infra.sarif._artifact_change import ArtifactChange
from onnxscript.diagnostics.infra.sarif._artifact_content import ArtifactContent
from onnxscript.diagnostics.infra.sarif._artifact_location import ArtifactLocation
from onnxscript.diagnostics.infra.sarif._attachment import Attachment
from onnxscript.diagnostics.infra.sarif._code_flow import CodeFlow
from onnxscript.diagnostics.infra.sarif._configuration_override import (
    ConfigurationOverride,
)
from onnxscript.diagnostics.infra.sarif._conversion import Conversion
from onnxscript.diagnostics.infra.sarif._edge import Edge
from onnxscript.diagnostics.infra.sarif._edge_traversal import EdgeTraversal
from onnxscript.diagnostics.infra.sarif._exception import Exception
from onnxscript.diagnostics.infra.sarif._external_properties import ExternalProperties
from onnxscript.diagnostics.infra.sarif._external_property_file_reference import (
    ExternalPropertyFileReference,
)
from onnxscript.diagnostics.infra.sarif._external_property_file_references import (
    ExternalPropertyFileReferences,
)
from onnxscript.diagnostics.infra.sarif._fix import Fix
from onnxscript.diagnostics.infra.sarif._graph import Graph
from onnxscript.diagnostics.infra.sarif._graph_traversal import GraphTraversal
from onnxscript.diagnostics.infra.sarif._invocation import Invocation
from onnxscript.diagnostics.infra.sarif._location import Location
from onnxscript.diagnostics.infra.sarif._location_relationship import (
    LocationRelationship,
)
from onnxscript.diagnostics.infra.sarif._logical_location import LogicalLocation
from onnxscript.diagnostics.infra.sarif._message import Message
from onnxscript.diagnostics.infra.sarif._multiformat_message_string import (
    MultiformatMessageString,
)
from onnxscript.diagnostics.infra.sarif._node import Node
from onnxscript.diagnostics.infra.sarif._notification import Notification
from onnxscript.diagnostics.infra.sarif._physical_location import PhysicalLocation
from onnxscript.diagnostics.infra.sarif._property_bag import PropertyBag
from onnxscript.diagnostics.infra.sarif._rectangle import Rectangle
from onnxscript.diagnostics.infra.sarif._region import Region
from onnxscript.diagnostics.infra.sarif._replacement import Replacement
from onnxscript.diagnostics.infra.sarif._reporting_configuration import (
    ReportingConfiguration,
)
from onnxscript.diagnostics.infra.sarif._reporting_descriptor import ReportingDescriptor
from onnxscript.diagnostics.infra.sarif._reporting_descriptor_reference import (
    ReportingDescriptorReference,
)
from onnxscript.diagnostics.infra.sarif._reporting_descriptor_relationship import (
    ReportingDescriptorRelationship,
)
from onnxscript.diagnostics.infra.sarif._result import Result
from onnxscript.diagnostics.infra.sarif._result_provenance import ResultProvenance
from onnxscript.diagnostics.infra.sarif._run import Run
from onnxscript.diagnostics.infra.sarif._run_automation_details import (
    RunAutomationDetails,
)
from onnxscript.diagnostics.infra.sarif._sarif_log import SarifLog
from onnxscript.diagnostics.infra.sarif._special_locations import SpecialLocations
from onnxscript.diagnostics.infra.sarif._stack import Stack
from onnxscript.diagnostics.infra.sarif._stack_frame import StackFrame
from onnxscript.diagnostics.infra.sarif._suppression import Suppression
from onnxscript.diagnostics.infra.sarif._thread_flow import ThreadFlow
from onnxscript.diagnostics.infra.sarif._thread_flow_location import ThreadFlowLocation
from onnxscript.diagnostics.infra.sarif._tool import Tool
from onnxscript.diagnostics.infra.sarif._tool_component import ToolComponent
from onnxscript.diagnostics.infra.sarif._tool_component_reference import (
    ToolComponentReference,
)
from onnxscript.diagnostics.infra.sarif._translation_metadata import TranslationMetadata
from onnxscript.diagnostics.infra.sarif._version_control_details import (
    VersionControlDetails,
)
from onnxscript.diagnostics.infra.sarif._web_request import WebRequest
from onnxscript.diagnostics.infra.sarif._web_response import WebResponse

# flake8: noqa
