# --------------------------------------------------------------------------
# ⚠️ WARNING - AUTO-GENERATED CODE - DO NOT EDIT ⚠️
# ⚙️ Generated by 'python -m opgen'
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# --------------------------------------------------------------------------
# pylint: disable=W0221,W0222,R0901,W0237
# mypy: disable-error-code=override
# ruff: noqa: N801,E741,RUF036,D214,D402,D405,D411,D412,D416,D417
# --------------------------------------------------------------------------

from __future__ import annotations

from typing import Optional, Tuple, TypeVar

from onnx.defs import get_schema

from onnxscript.onnx_opset._impl.opset26 import Opset26
from onnxscript.onnx_types import BFLOAT16, DOUBLE, FLOAT, FLOAT16, INT16, INT32, INT64
from onnxscript.values import Op, Opset


class Opset27(Opset26):
    def __new__(cls):
        return Opset.__new__(cls, "", 27)

    T_CausalConvWithState = TypeVar("T_CausalConvWithState", BFLOAT16, FLOAT, FLOAT16)

    def CausalConvWithState(
        self,
        input: T_CausalConvWithState,
        weight: T_CausalConvWithState,
        bias: Optional[T_CausalConvWithState] = None,
        past_state: Optional[T_CausalConvWithState] = None,
        *,
        activation: str = "none",
    ) -> Tuple[T_CausalConvWithState, T_CausalConvWithState]:
        r"""[🌐 CausalConvWithState(27)](https://onnx.ai/onnx/operators/onnx__CausalConvWithState.html#causalconvwithstate-27 "Online Documentation")



        Stateful causal 1D depthwise convolution.

        Used by Gated DeltaNet (Qwen3.5) and Mamba (Jamba, FalconMamba) as a preprocessing step.
        Replaces the 3-op pattern (Concat + Conv + Slice) with a single fused operation.

        The convolution is causal (looks only at current and past positions) and depthwise
        (each channel is convolved independently with its own kernel).

        The input, weight, past_state, output, and present_state tensors are rank-3 with
        shape (batch_size, channels, length). The optional bias input is rank-1 with
        shape (channels). For higher-dimensional data, use Reshape nodes before and
        after this operator to pack extra dimensions into the batch or channel axis.

        Weight layout: (channels, 1, k) for depthwise convolution.
        The carry state stores the last (k-1) positions for incremental decode.

        The optional activation attribute supports fused SiLU/Swish activation.



        Args:
            input: (differentiable) Input tensor with shape (batch_size, channels,
                length). Channels-first layout.

            weight: (differentiable) Depthwise convolution kernel with shape (channels,
                1, k) where k is the kernel size. The middle dim of size 1 follows the
                ONNX `Conv` weight layout `(M, C/group, k1, ..., kn)`: since this op is
                always depthwise, `group = channels`, so `C/group = 1`. Keeping this
                layout makes the weight tensor a drop-in for a depthwise
                `Conv(group=channels)` weight, so `Conv` <-> `CausalConvWithState`
                rewrites require no reshape.

            bias: (optional, differentiable) Optional per-channel bias with shape
                (channels).

            past_state: (optional, non-differentiable) Carry state from previous step
                with shape (batch_size, channels, k - 1). If not provided, padding is
                zero.

            activation: Fused activation function. One of: 'silu', 'swish', 'none'.
                Default is 'none'.
        """

        schema = get_schema("CausalConvWithState", 27, "")
        op = Op(self, "CausalConvWithState", schema)
        return op(
            *self._prepare_inputs(schema, input, weight, bias, past_state),
            activation=activation,
        )

    T_LinearAttention = TypeVar("T_LinearAttention", BFLOAT16, FLOAT, FLOAT16)

    S_LinearAttention = TypeVar("S_LinearAttention", BFLOAT16, FLOAT, FLOAT16)

    def LinearAttention(
        self,
        query: T_LinearAttention,
        key: T_LinearAttention,
        value: T_LinearAttention,
        past_state: Optional[S_LinearAttention] = None,
        decay: Optional[T_LinearAttention] = None,
        beta: Optional[T_LinearAttention] = None,
        *,
        chunk_size: int = 64,
        kv_num_heads: int,
        q_num_heads: int,
        scale: float = 0.0,
        update_rule: str = "gated_delta",
    ) -> Tuple[T_LinearAttention, S_LinearAttention]:
        r"""[🌐 LinearAttention(27)](https://onnx.ai/onnx/operators/onnx__LinearAttention.html#linearattention-27 "Online Documentation")


        Unified linear attention operator for autoregressive decoding (T=1) and prefill (T>1).

        The query, key, value, and (where applicable) decay/beta inputs use 3D packed format
        [B, T, H*D], where heads are flattened into the last dimension; q_num_heads and
        kv_num_heads are always required and are used to unpack to 4D internally for computation.
        The optional past_state and present_state are 4D with shape (B, H_kv, d_k, d_v).

        Group-query attention (GQA) is supported: q_num_heads must be a positive multiple of
        kv_num_heads. When q_num_heads == kv_num_heads this reduces to multi-headed linear
        attention; when q_num_heads > kv_num_heads each KV head (and its recurrent state) is
        shared by `q_num_heads / kv_num_heads` query heads (multi-query attention is the
        special case kv_num_heads == 1).

        The update_rule attribute selects the recurrence type:
        - "linear": S_t = S_{t-1} + k_t ⊗ v_t; o_t = scale * q_t^T S_t
        - "gated": S_t = exp(g_t) * S_{t-1} + k_t ⊗ v_t; o_t = scale * q_t^T S_t
        - "delta": S_t = S_{t-1} + β_t * k_t ⊗ (v_t - S_{t-1}^T k_t); o_t = scale * q_t^T S_t
        - "gated_delta": S_t = exp(g_t) * S_{t-1} + β_t * k_t ⊗ (v_t - exp(g_t) * S_{t-1}^T k_t); o_t = scale * q_t^T S_t

        where g_t is the decay (in log-space), β_t is the update rate, and ⊗ denotes outer product.

        Semantics: Equivalent to running the recurrent update sequentially for each token,
        but may be implemented using chunk-parallel algorithms for GPU efficiency.



        Args:
            query: (differentiable) Query vectors with 3D packed shape (B, T, H_q *
                d_k). Heads are packed into the last dimension.

            key: (differentiable) Key vectors with 3D packed shape (B, T, H_kv * d_k).
                Should be L2-normalized for delta/gated_delta modes.

            value: (differentiable) Value vectors with 3D packed shape (B, T, H_kv *
                d_v).

            past_state: (optional, non-differentiable) Recurrent state from previous
                step with shape (B, H_kv, d_k, d_v). Always 4D. If not provided,
                defaults to zeros.

            decay: (optional, differentiable) Exponential decay gate in log-space. 3D
                packed shape: (B, T, H_kv * d_k) for per-key-dimension decay
                (GLA/RWKV-6), or (B, T, H_kv) for per-head scalar decay
                (DeltaNet/RetNet). Required for 'gated' and 'gated_delta' modes.

            beta: (optional, differentiable) Update rate (sigmoid output). 3D packed
                shape: (B, T, H_kv) or (B, T, 1). Required for 'delta' and 'gated_delta'
                modes.

            chunk_size: Chunk size for the chunk-parallel WY decomposition during
                prefill (T>1). Tuning hint; does not affect output correctness.

            kv_num_heads: Number of key/value heads. Always required.

            q_num_heads: Number of query heads. Always required.

            scale: Output scaling factor. When 0.0 (default), derives d_k =
                query.shape[-1] / q_num_heads and uses 1/sqrt(d_k). Set explicitly to
                override.

            update_rule: The update rule for the linear attention recurrence. One of:
                'linear', 'gated', 'delta', 'gated_delta'. Default is 'gated_delta'.
        """

        schema = get_schema("LinearAttention", 27, "")
        op = Op(self, "LinearAttention", schema)
        return op(
            *self._prepare_inputs(schema, query, key, value, past_state, decay, beta),
            chunk_size=chunk_size,
            kv_num_heads=kv_num_heads,
            q_num_heads=q_num_heads,
            scale=scale,
            update_rule=update_rule,
        )

    T_Range = TypeVar("T_Range", BFLOAT16, DOUBLE, FLOAT, FLOAT16, INT16, INT32, INT64)

    def Range(
        self, start: T_Range, limit: T_Range, delta: T_Range, *, stash_type: int = 1
    ) -> T_Range:
        r"""[🌐 Range(27)](https://onnx.ai/onnx/operators/onnx__Range.html#range-27 "Online Documentation")


        Generate a tensor containing a sequence of numbers that begin at `start` and extends by increments of `delta`
        up to `limit` (exclusive).

        The number of elements in the output of range is computed as below:
        ::

            number_of_elements = max( ceil( (limit - start) / delta ) , 0 )


        The pseudocode determining the contents of the output is shown below:
        ::

            for(int i=0; i<number_of_elements; ++i) {
              output[i] =  start + (i * delta);
            }


        Example 1:
        ::

            Inputs: start = 3, limit = 9, delta = 3
            Output: [3, 6]


        Example 2:
        ::

            Inputs: start = 10, limit = 4, delta = -2
            Output: [10, 8, 6]



        For `float16` and `bfloat16` inputs, the `stash_type` attribute controls the precision used for
        intermediate accumulation. Setting `stash_type` to `1` (float) causes `start`, `limit`, and
        `delta` to be cast to 32-bit float before the loop, with the output cast back to the original
        type. This avoids precision loss for large ranges where successive additions in float16 or
        bfloat16 would otherwise be inexact (e.g. `x + 1 == x` for large `x`).


        Args:
            start: Scalar. First entry for the range of output values.

            limit: Scalar. Exclusive upper limit for the range of output values.

            delta: Scalar. Value to step by.

            stash_type: The data type used for intermediate computation when T is
                float16 or bfloat16. Defaults to 1 (float). Has no effect for other
                types.
        """

        schema = get_schema("Range", 27, "")
        op = Op(self, "Range", schema)
        return op(
            *self._prepare_inputs(schema, start, limit, delta), stash_type=stash_type
        )
