# --------------------------------------------------------------------------
# ⚠️ WARNING - AUTO-GENERATED CODE - DO NOT EDIT ⚠️
# ⚙️ Generated by 'python -m opgen'
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# --------------------------------------------------------------------------
# pylint: disable=W0221,W0222,R0901,W0237
# mypy: disable-error-code=override
# ruff: noqa: N801,E741,RUF036,D214,D402,D405,D411,D412,D416,D417
# --------------------------------------------------------------------------

from __future__ import annotations

from typing import TypeVar

from onnx.defs import get_schema

from onnxscript.onnx_opset._impl.opset25 import Opset25
from onnxscript.onnx_types import (
    BFLOAT16,
    DOUBLE,
    FLOAT,
    FLOAT16,
    INT32,
    INT64,
    UINT32,
    UINT64,
)
from onnxscript.values import Op, Opset


class Opset26(Opset25):
    def __new__(cls):
        return Opset.__new__(cls, "", 26)

    T_CumProd = TypeVar(
        "T_CumProd", BFLOAT16, DOUBLE, FLOAT, FLOAT16, INT32, INT64, UINT32, UINT64
    )

    T2_CumProd = TypeVar("T2_CumProd", INT32, INT64)

    def CumProd(
        self, x: T_CumProd, axis: T2_CumProd, *, exclusive: int = 0, reverse: int = 0
    ) -> T_CumProd:
        r"""[🌐 CumProd(26)](https://onnx.ai/onnx/operators/onnx__CumProd.html#cumprod-26 "Online Documentation")


        Performs cumulative product of the input elements along the given axis.
        By default, it will do the product inclusively meaning the first element is copied as is.
        Through an `exclusive` attribute, this behavior can change to exclude the first element.
        It can also perform product in the opposite direction of the axis. For that, set `reverse` attribute to 1.

        Example:
        ::

            input_x = [1, 2, 3]
            axis=0
            output = [1, 2, 6]
            exclusive=1
            output = [1, 1, 2]
            exclusive=0
            reverse=1
            output = [6, 6, 3]
            exclusive=1
            reverse=1
            output = [6, 3, 1]




        Args:
            x: (differentiable) An input tensor that is to be processed.

            axis: (non-differentiable) A 0-D tensor. Must be in the range [-rank(x),
                rank(x)-1]. Negative value means counting dimensions from the back.

            exclusive: If set to 1 will return exclusive product in which the top
                element is not included. In other terms, if set to 1, the j-th output
                element would be the product of the first (j-1) elements. Otherwise, it
                would be the product of the first j elements.

            reverse: If set to 1 will perform the products in reverse direction.
        """

        schema = get_schema("CumProd", 26, "")
        op = Op(self, "CumProd", schema)
        return op(*self._prepare_inputs(schema, x, axis), exclusive=exclusive, reverse=reverse)
