# --------------------------------------------------------------------------
# ⚠️ WARNING - AUTO-GENERATED CODE - DO NOT EDIT ⚠️
# ⚙️ Generated by 'python -m opgen'
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# --------------------------------------------------------------------------
# pylint: disable=W0221,W0222,R0901,W0237
# mypy: disable-error-code=override
# ruff: noqa: N801,E741,RUF036,D214,D402,D405,D411,D412,D416,D417
# --------------------------------------------------------------------------

from __future__ import annotations

from typing import Optional, TypeVar

from onnx import GraphProto
from onnx.defs import get_schema

from onnxscript.onnx_types import BFLOAT16, DOUBLE, FLOAT, FLOAT16
from onnxscript.values import Op, Opset


class Opset_ai_onnx_preview1(Opset):
    def __new__(cls):
        return Opset.__new__(cls, "ai.onnx.preview", 1)

    T1_FlexAttention = TypeVar("T1_FlexAttention", BFLOAT16, DOUBLE, FLOAT, FLOAT16)

    def FlexAttention(
        self,
        Q: T1_FlexAttention,
        K: T1_FlexAttention,
        V: T1_FlexAttention,
        *,
        prob_mod: Optional[GraphProto] = None,
        scale: Optional[float] = None,
        score_mod: Optional[GraphProto] = None,
        softmax_precision: Optional[int] = None,
    ) -> T1_FlexAttention:
        r"""[🌐 ai.onnx.preview::FlexAttention(1)](https://onnx.ai/onnx/operators/onnx_aionnxpreview_FlexAttention.html#flexattention-1 "Online Documentation")


        Computes scaled dot-product attention over rank-4 (batched, multi-head) inputs,
        with optional user-provided customization subgraphs at two stages:

        1. score_mod: Modify the attention score tensor after Q·K^T
        2. prob_mod: Modify the probability tensor after Softmax

        This operator mirrors the capabilities of PyTorch's flex_attention:
        https://docs.pytorch.org/docs/stable/nn.attention.flex_attention.html

        Input Shapes (MUST be rank-4 tensors):
        - Q: `(batch_size, q_num_heads, q_sequence_length, head_size)`
        - K: `(batch_size, kv_num_heads, kv_sequence_length, head_size)`
        - V: `(batch_size, kv_num_heads, kv_sequence_length, v_head_size)`

        Output Shape:
        - Y: `(batch_size, q_num_heads, q_sequence_length, v_head_size)`

        FlexAttention Computation:
        ::

            Scores = (Q @ K^T) * scale
            Scores = score_mod(Scores)             # if 'score_mod' is provided
            Probs = Softmax(Scores, axis=-1)
            Probs = prob_mod(Probs)                # if 'prob_mod' is provided
            Y = Probs @ V



        Grouped Query Attention (GQA):
        When `q_num_heads != kv_num_heads`, each K/V head is shared by a contiguous
        group of query heads in head-index order. Let
        `group_size = q_num_heads / kv_num_heads`; then query head `h` uses K/V head
        `floor(h / group_size)`. `q_num_heads` must be a multiple of
        `kv_num_heads`.

        Modifier Subgraphs (score_mod, prob_mod):
        Each modifier subgraph takes exactly one rank-4 tensor input and must produce
        exactly one rank-4 tensor output of the same shape and element type.
        - score_mod input/output shape: `(batch_size, q_num_heads, q_sequence_length, kv_sequence_length)`
        - prob_mod  input/output shape: `(batch_size, q_num_heads, q_sequence_length, kv_sequence_length)`
        The element type is determined by softmax_precision (defaults to float32 for
        non-double inputs, otherwise double).

        Masking can be expressed in score_mod by writing masked positions as -inf (or a
        large negative value appropriate for the target precision).


        Args:
            Q: Query tensor with shape `(batch_size, q_num_heads, q_seq_len,
                head_size)`.

            K: Key tensor with shape `(batch_size, kv_num_heads, kv_seq_len,
                head_size)`.

            V: Value tensor with shape `(batch_size, kv_num_heads, kv_seq_len,
                v_head_size)`.

            prob_mod: Optional probability modifier subgraph with 1 rank-4 tensor input
                and 1 rank-4 tensor output of the same shape and element type: (probs)
                -> probs_out. probs has softmax_precision element type and shape (B, Hq,
                L, S). The output must preserve the input shape.

            scale: Scaling factor for Q*K^T. Defaults to 1/sqrt(head_size).

            score_mod: Optional score modifier subgraph with 1 rank-4 tensor input and 1
                rank-4 tensor output of the same shape and element type: (scores) ->
                scores_out. scores has softmax_precision element type and shape (B, Hq,
                L, S). The output must preserve the input shape.

            softmax_precision: Floating-point precision for softmax computation.
                Defaults to float32 for non-double inputs, otherwise uses double. Must
                be explicitly specified for non-float types.
        """

        schema = get_schema("FlexAttention", 1, "ai.onnx.preview")
        op = Op(self, "FlexAttention", schema)
        return op(
            *self._prepare_inputs(schema, Q, K, V),
            prob_mod=prob_mod,
            scale=scale,
            score_mod=score_mod,
            softmax_precision=softmax_precision,
        )
