# Copyright (c) ONNX Project Contributors
# SPDX-License-Identifier: Apache-2.0

"""Rewrite rules for replacing block-diagonal packed attention with custom ops.

The Qwen3-VL vision encoder uses a block-diagonal attention mask to prevent
cross-image attention in packed sequences.  This module provides rewrite rules
that match the block-diagonal attention pattern and replace it with a
``com.microsoft::PackedMultiHeadAttention`` custom op for better runtime
performance on ONNX Runtime.

These rules are **not applied by default**.  Apply them post-export::

    from mobius.rewrite_rules import packed_attention_rules
    from onnxscript.rewriter import rewrite

    model = build("Qwen/Qwen3-VL-2B-Instruct")
    rewrite(model, pattern_rewrite_rules=packed_attention_rules())
"""

from __future__ import annotations

import numpy as np
import onnx_ir as ir
from onnxscript.rewriter._basics import MatchResult
from onnxscript.rewriter._rewrite_rule import RewriteRuleClassBase, RewriteRuleSet

from mobius.components._common import INT64_MAX


class BlockDiagonalToPackedMHA(RewriteRuleClassBase):
    """Replace block-diagonal masked Attention with PackedMultiHeadAttention.

    **Matched pattern** (generated by ``Qwen3VLVisionAttention``):

    1. Q, K, V are 2-D tensors ``(total_seq, hidden)`` that get
       ``Unsqueeze([0])`` to add a dummy batch dimension.
    2. A block-diagonal attention bias is built from ``segment_ids``
       (derived from ``cu_seqlens``) via ``Equal → Where(0, -10000)``.
    3. The bias is ``Unsqueeze([0, 1])`` to 4-D.
    4. ``Attention(Q_4d, K_4d, V_4d, bias_4d, ...)`` is called.
    5. The result is ``Squeeze([0])`` back to 2-D.

    **Replacement:**

    Compute ``token_offset`` from ``cu_seqlens`` and call
    ``com.microsoft::PackedMultiHeadAttention(Q, K, V, None,
    token_offset, cu_seqlens)``.
    """

    # ------------------------------------------------------------------ pattern

    def pattern(self, op, q, k, v, attn_bias_2d):
        q_4d = op.Unsqueeze(q, [0])
        k_4d = op.Unsqueeze(k, [0])
        v_4d = op.Unsqueeze(v, [0])
        attn_bias_4d = op.Unsqueeze(attn_bias_2d, [0, 1])
        attn_out = op.Attention(
            q_4d,
            k_4d,
            v_4d,
            attn_bias_4d,
            _allow_other_attributes=True,
            _outputs=["attn_out"],
        )
        return op.Squeeze(attn_out, [0])

    # ------------------------------------------------------------------ check

    def check(self, context, attn_bias_2d, attn_out, **_):
        result = MatchResult()

        # ---- verify block-diagonal mask structure ----
        where = attn_bias_2d.producer()
        if where is None or where.op_type != "Where":
            return result.fail("Expected Where producing attention bias")

        equal = where.inputs[0].producer()
        if equal is None or equal.op_type != "Equal":
            return result.fail("Expected Equal in mask condition")

        unsq_row = equal.inputs[0].producer()
        unsq_col = equal.inputs[1].producer()
        if not (
            unsq_row
            and unsq_col
            and unsq_row.op_type == "Unsqueeze"
            and unsq_col.op_type == "Unsqueeze"
        ):
            return result.fail("Expected Unsqueeze ops feeding Equal")

        # Both Unsqueezes must share the same segment_ids source
        if unsq_row.inputs[0] is not unsq_col.inputs[0]:
            return result.fail("Unsqueezes must share same segment_ids")

        # ---- trace segment_ids chain ----
        segment_ids = unsq_row.inputs[0]
        sub = segment_ids.producer()
        if sub is None or sub.op_type != "Sub":
            return result.fail("Expected Sub in segment_ids chain")
        reduce_sum = sub.inputs[0].producer()
        if reduce_sum is None or reduce_sum.op_type != "ReduceSum":
            return result.fail("Expected ReduceSum in segment_ids chain")
        cast = reduce_sum.inputs[0].producer()
        if cast is None or cast.op_type != "Cast":
            return result.fail("Expected Cast in segment_ids chain")
        ge = cast.inputs[0].producer()
        if ge is None or ge.op_type != "GreaterOrEqual":
            return result.fail("Expected GreaterOrEqual in segment_ids chain")

        # cu_seqlens arrives via Unsqueeze as the second input of GreaterOrEqual
        cu_unsq = ge.inputs[1].producer()
        if cu_unsq is None or cu_unsq.op_type != "Unsqueeze":
            return result.fail("Expected Unsqueeze for cu_seqlens")

        # ---- validate Where constants (0.0 and large-negative) ----
        true_val = ir.convenience.get_const_tensor(where.inputs[1])
        false_val = ir.convenience.get_const_tensor(where.inputs[2])
        if true_val is None or not np.isclose(float(true_val.numpy()), 0.0, atol=1e-3):
            return result.fail("Where true branch must be ~0.0")
        if false_val is None or float(false_val.numpy()) > -100:
            return result.fail("Where false branch must be large negative")

        # ---- verify Attention attributes ----
        attn = attn_out.producer()
        if attn.attributes.get_float("scale", None) is None:
            return result.fail("Missing scale attribute on Attention")
        if attn.attributes.get_int("q_num_heads", None) is None:
            return result.fail("Missing q_num_heads attribute on Attention")

        return result

    # ------------------------------------------------------------------ helpers

    @staticmethod
    def _trace_cu_seqlens(attn_bias_2d: ir.Value) -> ir.Value:
        """Walk backward from 2-D attention bias to original ``cu_seqlens``.

        Path: Where → Equal → Unsqueeze → segment_ids → Sub →
        ReduceSum → Cast → GreaterOrEqual → Unsqueeze → **cu_seqlens**
        """
        where = attn_bias_2d.producer()  # Where
        equal = where.inputs[0].producer()  # Equal
        seg_unsq = equal.inputs[0].producer()  # Unsqueeze (row)
        segment_ids = seg_unsq.inputs[0]  # segment_ids
        sub = segment_ids.producer()  # Sub
        reduce_sum = sub.inputs[0].producer()  # ReduceSum
        cast = reduce_sum.inputs[0].producer()  # Cast
        ge = cast.inputs[0].producer()  # GreaterOrEqual
        cu_unsq = ge.inputs[1].producer()  # Unsqueeze
        return cu_unsq.inputs[0]  # cu_seqlens

    # ------------------------------------------------------------------ rewrite

    def rewrite(self, op, q, k, v, attn_bias_2d, attn_out, **_):
        # Original Attention attributes
        attn = attn_out.producer()
        scale = attn.attributes.get_float("scale")
        num_heads = attn.attributes.get_int("q_num_heads")

        cu_seqlens = self._trace_cu_seqlens(attn_bias_2d)
        cu_seqlens_i32 = op.Cast(cu_seqlens, to=6)  # INT32

        # Reusable constant tensors (rewrite context needs ir.Value, not lists)
        axes_0 = op.Constant(value_ints=[0])
        axes_1 = op.Constant(value_ints=[1])
        neg_one = op.Constant(value_ints=[-1])
        int_max = op.Constant(value_ints=[INT64_MAX])
        slice_start_0 = op.Constant(value_ints=[0])
        slice_start_1 = op.Constant(value_ints=[1])

        # ---- token_offset computation ----
        # num_patches = len(cu_seqlens) - 1
        num_patches = op.Cast(
            op.Sub(op.Size(cu_seqlens), op.Constant(value_int=1)),
            to=6,
        )

        # Sub-sequence lengths and maximum length
        starts = op.Slice(cu_seqlens_i32, slice_start_0, neg_one, axes_0)
        ends = op.Slice(cu_seqlens_i32, slice_start_1, int_max, axes_0)
        lengths = op.Sub(ends, starts)
        max_length = op.Squeeze(op.ReduceMax(lengths), axes_0)

        # Position matrix (num_patches x max_length) in int32
        zero_i32 = op.Cast(op.Constant(value_int=0), to=6)
        one_i32 = op.Cast(op.Constant(value_int=1), to=6)
        rows = op.Range(zero_i32, num_patches, one_i32)
        cols = op.Range(zero_i32, max_length, one_i32)
        pos_matrix = op.Add(
            op.Mul(op.Unsqueeze(rows, axes_1), max_length),
            op.Unsqueeze(cols, axes_0),
        )
        pos_shape = op.Shape(pos_matrix)

        # Build token_offset: valid positions first, then padding
        mask_2d = op.Less(op.Unsqueeze(cols, axes_0), op.Unsqueeze(lengths, axes_1))
        mask_1d = op.Reshape(mask_2d, neg_one)
        pos_1d = op.Reshape(pos_matrix, neg_one)
        valid = op.Compress(pos_1d, mask_1d)
        padded = op.Compress(pos_1d, op.Not(mask_1d))
        token_offset = op.Reshape(op.Concat(valid, padded, axis=0), pos_shape)

        # com.microsoft::PackedMultiHeadAttention
        return op.op(
            "PackedMultiHeadAttention",
            inputs=[q, k, v, None, token_offset, cu_seqlens_i32],
            domain="com.microsoft",
            attributes={"scale": scale, "num_heads": num_heads},
        )


def packed_attention_rules() -> RewriteRuleSet:
    """Return rules that replace block-diagonal attention with PackedMHA.

    These rules match the packed-sequence attention pattern emitted by the
    Qwen3-VL vision encoder (segment mask from ``cu_seqlens`` +
    standard ONNX ``Attention`` op) and replace it with the Microsoft
    ``PackedMultiHeadAttention`` custom op for optimised inference on
    ONNX Runtime.

    Returns:
        :class:`RewriteRuleSet` containing the block-diagonal → packed MHA rule.
    """
    return RewriteRuleSet([BlockDiagonalToPackedMHA().rule()])
