#!/usr/bin/env python3
# Copyright (c) ONNX Project Contributors
# SPDX-License-Identifier: Apache-2.0

"""Auto-generate docs/feature-flags.md from the _Flags dataclass.

Run this script whenever a flag is added or modified::

    python docs/_generate_flags_docs.py

The generated file is committed to the repository.  A CI check (see
``.github/workflows/check-flags-docs.yml``) verifies it is up to date.

Extraction strategy
-------------------
For each field in :class:`mobius._flags._Flags`:

* **Name** — from ``dataclasses.fields()``.
* **Env var** — parsed from the ``_env_bool("ENV_VAR", default)`` call
  inside the field's ``default_factory`` lambda via the source AST.
* **Default** — the second argument to ``_env_bool`` in the same AST node.
* **Docstring** — the string-literal ``Expr`` node immediately following the
  field's ``AnnAssign`` node in the class body.
"""

from __future__ import annotations

import ast
import inspect
import sys
import textwrap
from pathlib import Path

# Resolve paths relative to repo root (this script lives in scripts/).
_REPO_ROOT = Path(__file__).parent.parent
_OUTPUT = _REPO_ROOT / "docs" / "feature-flags.md"

# Add src/ to the path so we can import mobius without an editable install.
sys.path.insert(0, str(_REPO_ROOT / "src"))

from mobius._flags import _Flags  # noqa: E402 (after sys.path manipulation)

# ---------------------------------------------------------------------------
# AST extraction helpers
# ---------------------------------------------------------------------------


def _parse_class_ast(cls: type) -> ast.ClassDef:
    """Return the ``ClassDef`` AST node for *cls*."""
    source = textwrap.dedent(inspect.getsource(cls))
    tree = ast.parse(source)
    return next(n for n in ast.walk(tree) if isinstance(n, ast.ClassDef))


def _extract_field_docstrings(class_def: ast.ClassDef) -> dict[str, str]:
    """Map field names → per-field docstring (string literal after the field)."""
    docs: dict[str, str] = {}
    body = class_def.body
    for i, node in enumerate(body):
        if not (isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name)):
            continue
        name = node.target.id
        if i + 1 < len(body):
            nxt = body[i + 1]
            if (
                isinstance(nxt, ast.Expr)
                and isinstance(nxt.value, ast.Constant)
                and isinstance(nxt.value.value, str)
            ):
                docs[name] = nxt.value.value.strip()
    return docs


def _extract_env_info(class_def: ast.ClassDef) -> dict[str, tuple[str, bool]]:
    """Map field names → (env_var_name, default_value) from _env_bool calls."""
    info: dict[str, tuple[str, bool]] = {}
    for node in class_def.body:
        if not (isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name)):
            continue
        name = node.target.id
        if node.value is None:
            continue
        # Walk node.value looking for Lambda → _env_bool(env_var, default)
        for sub in ast.walk(node.value):
            if not isinstance(sub, ast.Lambda):
                continue
            body = sub.body
            if (
                isinstance(body, ast.Call)
                and isinstance(body.func, ast.Name)
                and body.func.id == "_env_bool"
                and len(body.args) >= 2
                and isinstance(body.args[0], ast.Constant)
                and isinstance(body.args[1], ast.Constant)
            ):
                env_var: str = body.args[0].value
                default: bool = bool(body.args[1].value)
                info[name] = (env_var, default)
                break
    return info


# ---------------------------------------------------------------------------
# Markdown generation
# ---------------------------------------------------------------------------

_STATIC_PREAMBLE = """\
<!-- This file is AUTO-GENERATED by docs/_generate_flags_docs.py.
     Do NOT edit it by hand — run the script instead. -->

# Feature Flags

mobius exposes runtime feature flags that control experimental or
environment-specific behaviour. Flags live in `mobius._flags` and are
for **internal use only** — external callers configure them via environment
variables (see below).

"""

_STATIC_BODY = """
## Setting flags via environment variables

Environment variables are read when the global `flags` singleton is constructed
at import time. Set them before importing mobius (e.g., in a shell or `.env`):

```bash
# Example: disable warning suppression to see all deduplication warnings
export MOBIUS_SUPPRESS_DEDUP_WARNING=0

python -c "import mobius; mobius.build('Qwen/Qwen2.5-0.5B-Instruct')"
```

Accepted truthy values: `1`, `true`, `yes` (case-insensitive).\\
Accepted falsy values: `0`, `false`, `no` (case-insensitive).\\
Any other value falls back to the field default.

## Setting flags programmatically (internal code only)

Internal modules can import `flags` directly and assign to it:

```python
from mobius._flags import flags

flags.suppress_dedup_warning = False  # disable
flags.suppress_dedup_warning = True   # re-enable
```

## Using `override_flags()` in tests

For tests that need a temporary flag value, use the `override_flags` context
manager. It restores the original values on exit, even if the test raises:

```python
from mobius._flags import override_flags

def test_build_with_warnings(tmp_path):
    with override_flags(suppress_dedup_warning=False):
        pkg = mobius.build("Qwen/Qwen2.5-0.5B-Instruct")
    # suppress_dedup_warning is restored here
```

`override_flags` raises `ValueError` for unknown flag names, catching typos early.

> **Thread safety:** `override_flags` is not thread-safe — concurrent calls
> in different threads may interleave the save/restore cycle (TOCTOU).  For
> pytest, this is safe with `pytest -n auto` because xdist workers run in
> separate processes with independent flag singletons.

## Listing all flags

```python
from mobius._flags import list_flags

print(list_flags())
```

## Adding new flags

1. Add a field to `_Flags` in `src/mobius/_flags.py`:

   ```python
   my_new_flag: bool = dataclasses.field(
       default_factory=lambda: _env_bool("MOBIUS_MY_NEW_FLAG", False)
   )
   \"\"\"Short description of what my_new_flag controls.\"\"\"
   ```

2. Wire the flag into the code path it controls.

3. Regenerate this page:

   ```bash
   python docs/_generate_flags_docs.py
   ```

4. Add tests in `src/mobius/_flags_test.py` following existing patterns.
"""


def generate(output: Path = _OUTPUT) -> str:
    """Generate the feature-flags markdown and write it to *output*."""
    import dataclasses as dc

    class_def = _parse_class_ast(_Flags)
    field_docs = _extract_field_docstrings(class_def)
    env_info = _extract_env_info(class_def)

    # Build the flags reference table.
    table_rows: list[str] = []
    for field in dc.fields(_Flags):
        name = field.name
        env_var, default = env_info.get(name, (f"MOBIUS_{name.upper()}", "?"))
        doc = field_docs.get(name, "")
        # Collapse multi-line docstrings to a single line for the table cell.
        doc_single = " ".join(doc.split())
        default_str = str(default).lower()  # "true" / "false"
        table_rows.append(f"| `{name}` | `{env_var}` | `{default_str}` | {doc_single} |")

    table = (
        "## Available flags\n\n"
        "| Flag | Environment variable | Default | Description |\n"
        "|------|---------------------|---------|-------------|\n"
        + "\n".join(table_rows)
        + "\n"
    )

    content = _STATIC_PREAMBLE + table + _STATIC_BODY
    output.write_text(content, encoding="utf-8")
    print(f"Generated {output}")
    return content


if __name__ == "__main__":
    generate()
