trigger: none
name: onnxscript-publish.$(Date:yyyyMMdd).$(Rev:r)
resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  pipelines:
  - pipeline: onnxscript-release
    source: onnxscript-release
    trigger: true
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    stages:
    - stage: Release
      dependsOn: []
      jobs:
      - deployment: onnxscript_publish
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:
          - input: pipelineArtifact
            artifactName: drop
            pipeline: onnxscript-release
            targetPath: $(Pipeline.Workspace)/drop
        environment:
          name: 'onnxscript-release'
        pool:
          name: 'onnxruntime-Win-CPU-2022'
        strategy:
          runOnce:
            deploy:
              steps:
              - task: EsrpRelease@9
                displayName: 'ESRP Release'
                inputs:
                  connectedservicename: esrp_release
                  keyvaultname: 'ortbuildkeyvault'
                  signcertname: 'esrpcodesign'
                  clientid: '53d54d02-978d-4305-8572-583cf6711c4f'
                  contenttype: PyPi
                  folderlocation: '$(Pipeline.Workspace)/drop'
                  owners: 'justinchu@microsoft.com'
                  approvers: 'grama@microsoft.com'
                  mainpublisher: AIFrameworks
                  usemanagedidentity: true
                  domaintenantid: '975f013f-7f24-47e8-a7d3-abc4752bf346'
